"""Add encrypted_api_keys to tasks

Revision ID: a4f56fc73d60
Revises: c37109c69038
Create Date: 2025-11-14 05:39:59.105041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a4f56fc73d60'
down_revision: Union[str, Sequence[str], None] = 'c37109c69038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('encrypted_api_keys', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'encrypted_api_keys')
    # ### end Alembic commands ###
