"""Add session_id and branch_name to tasks, drop task_logs table

Revision ID: e5a994e9efd9
Revises: c37109c69038
Create Date: 2025-11-30 06:54:40.833727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5a994e9efd9'
down_revision: Union[str, Sequence[str], None] = 'c37109c69038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_logs_format'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_stream'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.add_column('tasks', sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tasks', sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'branch_name')
    op.drop_column('tasks', 'session_id')
    op.create_table('task_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('stream', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_logs_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_logs_pkey'))
    )
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_logs_stream'), 'task_logs', ['stream'], unique=False)
    op.create_index(op.f('ix_task_logs_format'), 'task_logs', ['format'], unique=False)
    # ### end Alembic commands ###
