"""Add repository_url to tasks table

Revision ID: 002a1a82a8b1
Revises: 97c87cda1d2a
Create Date: 2025-11-12 17:49:29.774038

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002a1a82a8b1"
down_revision: str | Sequence[str] | None = "97c87cda1d2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("repository_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "repository_url")
    # ### end Alembic commands ###
