"""remove branch_name and add parent_task_id to tasks

Revision ID: 042598a75103
Revises: e5a994e9efd9
Create Date: 2025-11-30 23:54:45.871079

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "042598a75103"
down_revision: str | Sequence[str] | None = "e5a994e9efd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("parent_task_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "tasks", "tasks", ["parent_task_id"], ["id"])
    op.drop_column("tasks", "branch_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("branch_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "parent_task_id")
    # ### end Alembic commands ###
