"""Add task_logs table

Revision ID: c37109c69038
Revises: 002a1a82a8b1
Create Date: 2025-11-12 21:19:33.527500

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c37109c69038"
down_revision: str | Sequence[str] | None = "002a1a82a8b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("stream", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_logs_format"), "task_logs", ["format"], unique=False)
    op.create_index(op.f("ix_task_logs_stream"), "task_logs", ["stream"], unique=False)
    op.create_index(
        op.f("ix_task_logs_task_id"), "task_logs", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_logs_task_id"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_stream"), table_name="task_logs")
    op.drop_index(op.f("ix_task_logs_format"), table_name="task_logs")
    op.drop_table("task_logs")
    # ### end Alembic commands ###
